apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customer-deployment
  labels:
    app: api-customer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-customer
  template:
    metadata:
      labels:
        app: api-customer
    spec:
      containers:
      - name: api-customer
        image: us.icr.io/docker_lab1/springboot-microservice-cloud:1.0
        ports:
        - containerPort: 8071
